# =============================================
# Configuración de Base de Datos MySQL
# =============================================
db.host=localhost
db.port=3306
db.name=crud_usuarios
db.username=root
db.password=admin

# =============================================
# Configuración SMTP (JavaMail)
# =============================================
smtp.host=smtp.gmail.com
smtp.port=587
smtp.username=insperb5013@gmail.com
smtp.password=psvj atsd uino lyho
smtp.from.address=insperb5013@gmail.com
smtp.from.name=Gestión de Usuarios

